### ISSUE TITLE
Websocket Error

### ISSUE THREAD

**Issue by smilerz** [danpaquin/gdax-python#255]
Within the last 24 hours or so the Websocket Client stopped working.  When attempting to start listening it throws the following error:
{'type': 'error', 'message': 'Failed to unsubscribe', 'reason': 'You need to specify at least one product ID for channel heartbeat'}

Then the whole thing dies out. with a "RuntimeError: cannot join current thread".

I attempted adding product_ids to the spots that call heartbeat.  I also attempted to explicitly join the heartbeat channel to no avail.  Commenting out the sections that reference heartbeat gets it working again.

**Comment by sdenenberg** [comment]
Same thing has started happening to me.  It was intermittent for a bit and now it happens everytime

**Comment by SorenJ89** [comment]
i guess its linked to what reported regarding the orderbook here https://github.com/danpaquin/gdax-python/issues/257

**Comment by sdenenberg** [comment]
As an update, the problem went away this morning and then came back this evening.  My code has not changed - anybody have any thoughts?

**Comment by jeffro256** [comment]
I have this problem also. I haven't changed any parts of the code directly related to the GDAX Websocket yet I started receiving this exact same error yesterday.

**Comment by sdenenberg** [comment]
It looks like we're not the only one having issues: 

https://github.com/coinbase/gdax-node/issues/113

My guess is something changed downstream.  I'll look at the suggestions above a little more closely, but I'm probably underqualified to debug this.

**Comment by gsmadi** [comment]
Fixed here [#258](https://github.com/danpaquin/gdax-python/pull/258).

**Comment by smilerz** [comment]
@gsmadi - I don't think that's the issue.  I'm not using orderbook at all, just the WebSocketClient.  And I'm not referencing sequence numbers either.

**Comment by sdenenberg** [comment]
@gsmadi @smilerz I verified that gsmadi's fix does work for the orderbook, but a similar change will be needed in the websocketclient to deal with the same first message from the heartbeat channel.  If you can't figure it out, let me know and I'll look into where it needs to be changed - right now I'm not using the websocket client.  I believe what I referenced in the coinbase git account more directly addresses your issue

**Comment by sdenenberg** [comment]
Incidentally, thanks @gsmadi!  Nice elegant fix to the orderbook.

**Comment by smilerz** [comment]
@sdenenberg I should have been more specific.  Yes, @gsmadi caught the OrderBook bug, but it still exists in the WebSocketClient.  I believe my initial workaround is actually the correct fix as it appears from reading the issue that you linked to that the heartbeat is redundant.  So commenting out the heartbeat calls is the right move.  Removing the ping I believe is also redundant.
The client could probably be updated to add the heartbeat channel by default.

At least that's how I'm interpreting what is going on, I'm a bit out of my depth.

**Comment by gsmadi** [comment]
@smilerz Aaah I see thanks for the insight. Will take a closer look. Probably GDAX has been tinkering around with the heartbeat channel thats causing this.

@sdenenberg Glad it helped on the OrderBook front!

I think this requires some a more in depth solution. If heartbeat subscribe/unsubscribe changed the most appropriate fix would be to address the change and/or enhance error handling. So my fix really is a patch for the OrderBook and commenting out is a temporary solution for the WebSocketClient. Not that heartbeat is that much necessary unless you are reconciling trades. But to keep things clean and consistent with how they have been, we should try to address any change.

**Comment by jebesen** [comment]
I have the same problem and my code was working ok few days ago.
The difference is that I'm not subscribing to 'heartbeat' channel. I am subscribing to 'tickers' channel but I'm getting the {'type': 'error', 'message': 'Failed to unsubscribe', 'reason': 'You need to specify at least one product ID for channel heartbeat'} error.

Any one with any ideas to solve this?

**Comment by llinsky** [comment]
Hey all, I fixed this by handling error messages in my on_message override: 

`if 'type' in msg and 'error' in msg['type']:
            print "Error message received: ", msg
            self.errors += 1
            if self.errors < 20:
                print 'Skipping error, total count: ', self.errors
                return
            else:
                print 'Too many errors: ', self.errors
                print 'Closing down!'
                self.close()
                return`

**Comment by jebesen** [comment]
Hi llisky,

Handling the error does not solve the problem with the subscription failure.  The problem is what makes this error raise, and was not happening a few days ago.

**Comment by llinsky** [comment]
The above code will work if you are overriding a Gdax websocket class and overriding on_message. You didn't post any code or error message output, but I assume you are getting an exception because you are not checking that the message is an error message before you try to index it. So you just need to check for that and handle error messages first. Good luck.

**Comment by jebesen** [comment]
I am already handling the errors in my on_message override. I have also noted that it is an 'unsubscription' error. But the only thing I know is that a few days ago the code was working smoothly and now I get that 'unsubscription' error when trying to connet so I can't subscribe to the tickers channel. At this point, handling the message error or not does not make any difference.  If it is an issue caused by GDAX nothing else to say. I hope they solve it soon.  Thank you anyway.

**Comment by walid0925** [comment]
@jebesen I've also noticed the same issue with the tickers channel. Let me know if you manage to find a workaround

**Comment by smilerz** [comment]
@walid0925 the work around I referenced above works.  I’ve been running without error for 2 days.

**Comment by jebesen** [comment]
@smilerz @walid09 I have looked into the " _connect' function and I've commented de following lines:

```
if self.type == "heartbeat":
             sub_params = {"type": "heartbeat", "on": True}
         else:
             sub_params = {"type": "heartbeat", "on": False}
```
Type is "subscribe" and Channels is "tickers" so I really do not get point of this lines.

Without these lines all appears to work perfect.  What puzzles me is that few days ago it was working ok with this lines.

**Comment by walid0925** [comment]
@smilerz @jebesen thanks for that! I thought that wouldn't affect the tickers channels as you said. Very strange, works for me now as well.

**Comment by mcardillo55** [comment]
#262 fixes this for anyone still following this thread

**Comment by mcardillo55** [comment]
#262 Was merged. This issue should be resolved.
